// Read-only independent production checkpoint. No scan-trigger or database writes.
import fs from 'node:fs/promises';import {createHash} from 'node:crypto';
const out='accuracy-independent-check';await fs.mkdir(out,{recursive:true});const base='https://football-edge-background-watch.ngophuonghuy.workers.dev';
async function get(p){const r=await fetch(base+p,{headers:{Authorization:'Bearer '+process.env.BACKGROUND_TOKEN},signal:AbortSignal.timeout(45000),cache:'no-store'});if(!r.ok)throw Error('READ_HTTP_'+r.status);return r.json();}
let accuracy,entries,complete=false;const maxPolls=Math.max(1,Math.min(90,Number(process.env.MAX_VERIFY_POLLS)||90));for(let i=0;i<maxPolls;i++){try{accuracy=await get('/api/notify/accuracy');entries=(await get('/api/db/export/entries?limit=10000')).rows;const pendingHistorical=entries.filter(x=>['FT','H1'].includes(x.engine)&&x.auto_settle_supported&&x.captured_at<Date.now()-12*3600000&&x.odds_format==='DEC'&&['OVER','UNDER'].includes(x.selection)&&x.line!==null&&x.price>1&&x.resolution==='OPEN');if(accuracy.repair_revision===2&&accuracy.status?.repair_revision===2&&accuracy.backfill_complete&&!pendingHistorical.length){complete=true;break}}catch{}if(i+1<maxPolls)await new Promise(r=>setTimeout(r,10000));}
if(!complete)throw Error('REVISION_2_HISTORICAL_SETTLEMENT_NOT_VERIFIED');
const dbURL=`https://api.cloudflare.com/client/v4/accounts/${process.env.CLOUDFLARE_ACCOUNT_ID}/d1/database/0d12a7cc-12a9-4c71-b55b-61dfd2dac4d4/query`;
async function query(sql){if(!/^SELECT /i.test(sql))throw Error('NON_READ_QUERY_FORBIDDEN');const r=await fetch(dbURL,{method:'POST',headers:{Authorization:'Bearer '+process.env.CLOUDFLARE_API_TOKEN,'Content-Type':'application/json'},body:JSON.stringify({sql}),signal:AbortSignal.timeout(45000)});const d=await r.json();if(!r.ok||!d.success)throw Error('D1_READ_FAILED');return d.result[0].results;}
const outcomes=await query('SELECT * FROM entry_outcomes ORDER BY resolved_at DESC LIMIT 10000');
const periods=await query("SELECT * FROM validation_results WHERE validation_type IN ('ACCURACY_H1_PERIOD','ACCURACY_FT_PERIOD') AND id NOT IN (SELECT json_extract(payload_json,'$.prior_measurement_id') FROM validation_results WHERE json_extract(payload_json,'$.prior_measurement_id') IS NOT NULL) ORDER BY created_at LIMIT 1000");
const ids=[...new Set(outcomes.map(x=>x.fixture_id))].slice(0,60),fixtures=new Map();let calls=0;
for(const id of ids){calls++;const r=await fetch('https://v3.football.api-sports.io/fixtures?id='+id,{headers:{'x-apisports-key':process.env.APISPORTS_KEY},signal:AbortSignal.timeout(30000)});const d=await r.json();if(!r.ok||Object.keys(d.errors||{}).length)throw Error('OFFICIAL_FIXTURE_READ_FAILED');fixtures.set(id,d.response?.[0]);}
const num=x=>x!==null&&x!==undefined&&x!==''&&Number.isFinite(Number(x));const checks=[];
for(const o of outcomes){const e=entries.find(x=>x.id===o.decision_id),f=fixtures.get(o.fixture_id),sc=e?.engine==='H1'?f?.score?.halftime:f?.score?.fulltime;
  if(!e||!sc||!num(sc.home)||!num(sc.away)){checks.push({id:o.decision_id,status:'UNVERIFIABLE'});continue}
  if(o.outcome==='VOID'){checks.push({id:o.decision_id,status:'VOID_NOT_BET_LOSS'});continue}
  const legs=Math.round(e.line*4)%2?[Math.floor(e.line*2)/2,Math.ceil(e.line*2)/2]:[e.line],total=Number(sc.home)+Number(sc.away);
  const pl=legs.map(l=>{const delta=e.selection==='OVER'?total-l:l-total;return delta>0?Number(e.price)-1:delta<0?-1:0}).reduce((a,b)=>a+b,0)/legs.length;
  const original=JSON.parse(e.payload_json||'{}'),sourceLocked=Number(original.line)===Number(e.line)&&Number(original.price)===Number(e.price)&&original.policy_status===e.policy_status;
  const match=Math.abs(pl-Number(o.unit_pl))<1e-8&&Number(sc.home)===Number(o.final_score_home)&&Number(sc.away)===Number(o.final_score_away)&&sourceLocked&&e.resolution==='RESOLVED';
  checks.push({id:o.decision_id,fixture_id:e.fixture_id,engine:e.engine,policy:e.policy_status,status:match?'OFFICIAL_PAPER_MATCH':'MISMATCH',source_locked:sourceLocked});
}
if(checks.some(x=>x.status==='MISMATCH'))throw Error('PAPER_RESULT_REGRESSION');
if(!checks.some(x=>x.status==='OFFICIAL_PAPER_MATCH'))throw Error('NO_REAL_PAPER_OUTCOME_VERIFIED');
const r=await fetch('https://shiny-silence-d892.ngophuonghuy.workers.dev/?independent_accuracy='+Date.now(),{cache:'no-store',signal:AbortSignal.timeout(30000)}),hash=createHash('sha256').update(await r.text()).digest('hex');if(hash!=='157af7294df17b997f505a6fa0a4658699c8236808a643e29ca2d71bd1b8b392')throw Error('FRONTEND_CHANGED');
const report={at:new Date().toISOString(),production_mutations:false,accuracy,entries:entries.length,outcomes:outcomes.length,official_paper_matches:checks.filter(x=>x.status==='OFFICIAL_PAPER_MATCH').length,unique_settled_fixtures:ids.length,still_open_paper:entries.filter(x=>x.resolution==='OPEN'&&['FT','H1'].includes(x.engine)).length,period_rows:periods.length,period_pending:periods.filter(x=>x.result_key==='PENDING').length,provider_calls:calls,frontend_sha256:hash,notes:['Paper snapshots repeated across fixtures are not independent executable bets.','HC cover model and real iPhone click not independently verified.','Immutable original payload may retain OPEN while authoritative outcome columns are resolved.']};
await fs.writeFile(out+'/SUMMARY.json',JSON.stringify(report,null,2));await fs.writeFile(out+'/PAPER_CHECKS.json',JSON.stringify(checks));await fs.writeFile(out+'/PERIOD_ROWS.json',JSON.stringify(periods));console.log('INDEPENDENT_ACCURACY_CHECK '+JSON.stringify(report));
