import {createEngine} from './notify-core.js';
const legacyMarketEngine=createEngine();
const LIVE = new Set(['1H','HT','2H','ET','BT','P','INT','SUSP','LIVE']);
const clamp=(x,a=0,b=100)=>Math.max(a,Math.min(b,Number(x)||0));
const round=(x,n=2)=>{const p=10**n; return Math.round((Number(x)||0)*p)/p};
const safeJson=(s,f={})=>{try{return typeof s==='string'?JSON.parse(s):s??f}catch{return f}};
const toNum=(v)=>{if(v===null||v===undefined||v==='')return null;if(typeof v==='string'){const s=v.trim().replace('%','');if(!s)return null;const n=Number(s);return Number.isFinite(n)?n:null;}const n=Number(v);return Number.isFinite(n)?n:null;};
const statKey=(type)=>{const s=String(type||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();if(s==='shots on goal')return 'shots_on_goal';if(s==='total shots')return 'total_shots';if(s==='shots insidebox'||s==='shots inside box')return 'shots_inside_box';if(s==='blocked shots')return 'blocked_shots';if(s==='corner kicks'||s==='corners')return 'corners';if(s==='ball possession'||s==='possession')return 'possession';if(s==='red cards')return 'red_cards';if(s==='yellow cards')return 'yellow_cards';if(s==='expected goals'||s==='xg')return 'xg';return null;};
function normalizeStats(payload){const response=Array.isArray(payload?.response)?payload.response:[];const out={};for(const team of response){const tid=String(team?.team?.id??'');if(!tid)continue;const row={};for(const st of (team?.statistics||[])){const k=statKey(st?.type);if(!k)continue;row[k]=toNum(st?.value);}out[tid]=row;}return out;}
function normalizeEvents(payload){return Array.isArray(payload?.response)?payload.response:[];}
function teamIds(fixture){return [String(fixture?.teams?.home?.id??''),String(fixture?.teams?.away?.id??'')];}
function nearestElapsed(captures,ts,fallback=0){let best=null;const t=Date.parse(ts||'');for(const c of captures){const ct=Date.parse(c.received_at||'');if(Number.isFinite(t)&&Number.isFinite(ct)&&ct<=t&&(best===null||ct>best.t))best={t:ct,e:Number(c.match_clock||0)};}return best?.e||fallback||0;}
function delta(curr,prev,key){const a=curr?.[key],b=prev?.[key];if(a===null||a===undefined||b===null||b===undefined)return {v:0,available:false,correction:false};const d=Number(a)-Number(b);return {v:Math.max(0,d),available:true,correction:d<0};}
function intervalFeatures(obsA,obsB,fixture,events){if(!obsA||!obsB)return {status:'INSUFFICIENT_DATA',reasons:['NEED_TWO_STAT_CAPTURES']};const [h,a]=teamIds(fixture);if(!h||!a)return {status:'INSUFFICIENT_DATA',reasons:['TEAM_IDENTITY_MISSING']};const prev=obsA.stats[h]||{},cur=obsB.stats[h]||{},prevA=obsA.stats[a]||{},curA=obsB.stats[a]||{};const keys=['shots_on_goal','total_shots','shots_inside_box','blocked_shots','corners','red_cards','yellow_cards'];const base=new Set(['shots_on_goal','total_shots','corners']);let correction=false,availability=0,baseAvailability=0;const sides={home:{},away:{}};for(const [side,c,p] of [['home',cur,prev],['away',curA,prevA]]){for(const k of keys){const d=delta(c,p,k);sides[side][k]=d.v;correction||=d.correction;availability+=Number(d.available);if(base.has(k))baseAvailability+=Number(d.available);}sides[side].possession=c.possession??null;sides[side].xg=c.xg??null;}const interval=Math.max(1,(obsB.elapsed||0)-(obsA.elapsed||0)||Math.round((Date.parse(obsB.received_at)-Date.parse(obsA.received_at))/60000)||1);const payload={interval_min:interval,home:sides.home,away:sides.away,events:events||[],base_stats_availability_count:baseAvailability,stats_availability_count:availability,provider_correction_detected:correction,from_received_at:obsA.received_at,to_received_at:obsB.received_at};if(baseAvailability<6)return {status:'INSUFFICIENT_DATA',payload,reasons:['BASE_STATS_UNAVAILABLE',...(correction?['PROVIDER_CORRECTION_DETECTED']:[])]};return {status:'OK',payload,reasons:correction?['PROVIDER_CORRECTION_DETECTED']:[]};}
function pressure(feat){if(feat.status!=='OK')return {status:'INSUFFICIENT_DATA',reasons:['FEATURES_NOT_READY']};const score=v=>{const poss=v.possession;const possSupport=poss===null?0:Math.max(-5,Math.min(5,(poss-50)*.12));const raw=v.shots_on_goal*8+v.total_shots*3+v.shots_inside_box*3.5+v.blocked_shots*1.5+v.corners*2+possSupport;return clamp(raw*3.2)};const h=score(feat.payload.home),a=score(feat.payload.away),gap=h-a;const level=x=>x>=70?'HIGH':x>=40?'MODERATE':'LOW';return {status:'OK',home_score:round(h),away_score:round(a),home_level:level(h),away_level:level(a),gap:round(gap),dominant_side:gap>=15?'HOME':gap<=-15?'AWAY':'NEUTRAL'};}
function threat(feat){if(feat.status!=='OK')return {status:'INSUFFICIENT_DATA',reasons:['FEATURES_NOT_READY']};const score=v=>{let raw=v.shots_on_goal*12+v.shots_inside_box*7+v.blocked_shots*2+v.total_shots*1.5;if(v.xg!==null)raw+=Math.min(12,Number(v.xg)*4);return clamp(raw*2.7)};const h=score(feat.payload.home),a=score(feat.payload.away),level=x=>x>=70?'HIGH':x>=35?'MODERATE':'LOW';return {status:'OK',home_score:round(h),away_score:round(a),home_level:level(h),away_level:level(a)};}
function tempo(feat){if(feat.status!=='OK')return {status:'INSUFFICIENT_DATA',reasons:['FEATURES_NOT_READY']};const activity=v=>v.shots_on_goal*3+v.total_shots*1.4+v.shots_inside_box*1.8+v.blocked_shots*.8+v.corners*.7;const rate=(activity(feat.payload.home)+activity(feat.payload.away))/Math.max(1,feat.payload.interval_min);const score=clamp(rate*12);return {status:'OK',tempo_score:round(score),tempo_level:score>=70?'HIGH':score>=35?'MODERATE':'LOW',activity_rate:round(rate,3),interval_min:feat.payload.interval_min};}
function control(feat,p){if(feat.status!=='OK'||p.status!=='OK')return {status:'INSUFFICIENT_DATA',reasons:['CONTROL_DEPENDENCY_NOT_READY']};const hp=feat.payload.home.possession,ap=feat.payload.away.possession,possGap=(hp!==null&&ap!==null)?hp-ap:0;const gap=Math.max(-100,Math.min(100,p.gap*.65+possGap*.55));const strength=Math.min(100,Math.abs(gap));return {status:'OK',control_gap:round(gap),dominant_side:gap>=15?'HOME':gap<=-15?'AWAY':'NEUTRAL',control_strength:round(strength),control_level:strength>=60?'HIGH':strength>=25?'MODERATE':'LOW',possession_gap:round(possGap)};}
function momentum(observations,fixture,events){if(observations.length<3)return {status:'INSUFFICIENT_DATA',reasons:['NEED_THREE_STAT_CAPTURES_FOR_MOMENTUM']};const f0=intervalFeatures(observations.at(-3),observations.at(-2),fixture,events),f1=intervalFeatures(observations.at(-2),observations.at(-1),fixture,events);if(f0.status!=='OK'||f1.status!=='OK')return {status:'INSUFFICIENT_DATA',reasons:['MOMENTUM_FEATURES_NOT_READY']};const act=v=>v.shots_on_goal*8+v.total_shots*3+v.shots_inside_box*3.5+v.corners*2;const n0=act(f0.payload.home)-act(f0.payload.away),n1=act(f1.payload.home)-act(f1.payload.away),acc=n1-n0;return {status:'OK',direction:n1>=5?'HOME':n1<=-5?'AWAY':'NEUTRAL',trend:Math.abs(n1)>Math.abs(n0)+3?'RISING':Math.abs(n1)+3<Math.abs(n0)?'FALLING':'STABLE',strength:round(Math.min(100,Math.abs(n1)*4)),acceleration:round(acc)};}
function matchState(p,t,tp,c){if([p,t,tp,c].some(x=>x.status!=='OK'))return {status:'INSUFFICIENT_DATA',primary_state:'INSUFFICIENT_DATA',reasons:['MATCH_STATE_DEPENDENCY_NOT_READY']};const hp=p.home_score,ap=p.away_score,ht=t.home_score,at=t.away_score;let state='BALANCED',dom='NONE';if(tp.tempo_level==='LOW'&&hp<20&&ap<20&&ht<20&&at<20)state='LOW_TEMPO';else if(hp>=65&&ap>=65&&ht>=45&&at>=45)state='OPEN_GAME';else if(hp-ap>=20&&(ht>=35||hp>=75)){state='HOME_ATTACKING';dom='HOME';}else if(ap-hp>=20&&(at>=35||ap>=75)){state='AWAY_ATTACKING';dom='AWAY';}else if(hp-ap>=15){state='HOME_CONTROL';dom='HOME';}else if(ap-hp>=15){state='AWAY_CONTROL';dom='AWAY';}if(state==='BALANCED'&&['HOME','AWAY'].includes(c.dominant_side)&&Math.max(hp,ap)>=35){state=c.dominant_side+'_CONTROL';dom=c.dominant_side;}return {status:'OK',primary_state:state,dominant_side:dom,state_strength:round(Math.min(100,Math.max(Math.abs(hp-ap),Math.max(hp,ap)*.7))),tempo_level:tp.tempo_level,control_side:c.dominant_side};}
function goalPressure(p,t,s,tp,m){if([p,t,s,tp].some(x=>x.status!=='OK'))return {status:'INSUFFICIENT_DATA',reasons:['GP_DEPENDENCY_NOT_READY']};const calc=side=>{const ps=p[side+'_score'],ts=t[side+'_score'];let base=Math.min(ps,ts)*.65+(ps*ts/100)*.35;if(m.status==='OK'&&m.direction===side.toUpperCase()&&m.trend==='RISING')base+=7;if(tp.tempo_level==='HIGH')base+=3;else if(tp.tempo_level==='LOW')base=Math.min(base,72);return clamp(base)};const h=calc('home'),a=calc('away'),mx=Math.max(h,a);const mode=h>a+7?'HOME':a>h+7?'AWAY':h>=55&&a>=55?'TWO_SIDED':'NEUTRAL';return {status:'OK',home_score:round(h),away_score:round(a),mode,level:mx>=85?'VERY_HIGH':mx>=70?'HIGH':mx>=45?'MODERATE':'LOW',lifecycle:mx>=70?'ACTIVE':mx>=45?'BUILDING':'NONE'};}
function signal(gp){if(gp.status!=='OK')return {status:'INSUFFICIENT_DATA',signal_type:'NONE',lifecycle:'NONE',reasons:['GOAL_PRESSURE_NOT_READY']};const mx=Math.max(gp.home_score,gp.away_score);const type=gp.mode==='TWO_SIDED'&&mx>=70?'TWO_SIDED_ESCALATION':mx>=70?'GOAL_PRESSURE_ACTIVE':'NONE';return {status:'OK',signal_type:type,lifecycle:type==='NONE'?'NONE':'ACTIVE',side:['HOME','AWAY'].includes(gp.mode)?gp.mode:null,materiality:mx>=80?'HIGH':mx>=70?'MEDIUM':'LOW'};}
function dq(latestStats,observations,feat,receivedAt){const tids=Object.keys(latestStats||{}),hs=latestStats?.[tids[0]]||{},as=latestStats?.[tids[1]]||{};const fullKeys=['shots_on_goal','total_shots','shots_inside_box','blocked_shots','corners','possession'],baseKeys=['shots_on_goal','total_shots','corners'];const paired=k=>hs[k]!==null&&hs[k]!==undefined&&as[k]!==null&&as[k]!==undefined;const full=fullKeys.filter(paired).length,base=baseKeys.filter(paired).length;const mode=full===fullKeys.length?'FULL':base===baseKeys.length?'BASE':'LIMITED';const coverage=mode==='FULL'?100:mode==='BASE'?72:Math.round(100*base/baseKeys.length);const correction=!!feat?.payload?.provider_correction_detected,integrity=correction?80:100,age=Math.max(0,(Date.now()-Date.parse(receivedAt||0))/1000),freshness=age<=120?100:age<=300?80:age<=600?50:20,score=Math.round(coverage*.5+integrity*.3+freshness*.2);const confidence=score>=85&&observations.length>=3?'HIGH':score>=70&&observations.length>=2?'MEDIUM':'LOW',status=(['FULL','BASE'].includes(mode)&&score>=70)?'VALID':score>=50?'CAUTION':'UNVERIFIED';return {status:'OK',data_mode:mode,coverage,integrity,freshness,dq_score:score,confidence,validation_status:status};}
function entry(sig,dqv,gp){if(sig.status!=='OK'||dqv.status!=='OK')return {status:'INSUFFICIENT_DATA',state:'BLOCKED',substate:'BLOCKED_DATA'};if(dqv.validation_status==='UNVERIFIED'||dqv.confidence==='LOW')return {status:'OK',state:'BLOCKED',substate:'BLOCKED_DATA'};if(sig.lifecycle!=='ACTIVE')return {status:'OK',state:'WAIT',substate:'WAIT_BUILDING'};const mx=gp.status==='OK'?Math.max(gp.home_score,gp.away_score):0;return {status:'OK',state:mx>=75?'OPEN':'WAIT',substate:mx>=82?'OPEN_CORE':mx>=75?'OPEN_EARLY':'WAIT_CONFIRMING'};}
function novelty(sig,en,feat,events,clock){if(sig.status!=='OK'||en.status!=='OK'||feat.status!=='OK')return {status:'INSUFFICIENT_DATA',score:null,band:'N/A'};const f=feat.payload,total=['home','away'].reduce((s,side)=>s+['shots_on_goal','total_shots','shots_inside_box','corners'].reduce((a,k)=>a+(f[side][k]||0),0),0),structural=(events||[]).some(ev=>Number(ev?.time?.elapsed||ev?.elapsed||0)>=clock-f.interval_min&&['Goal','Card'].includes(ev?.type));let score=en.state==='OPEN'?16:sig.lifecycle==='ACTIVE'?12:Math.min(9,2+total*1.5);if(structural)score=Math.min(20,score+4);return {status:'OK',score:round(score),band:score>=15?'HIGH':score>=8?'MEDIUM':'LOW',structural_event_recent:structural};}
function flowChange(p,s,m){if(p.status!=='OK'||s.status!=='OK')return {status:'INSUFFICIENT_DATA',score:null,band:'N/A'};let score=Math.min(9,Math.abs(p.gap)*.12);if(m.status==='OK'){if(m.trend==='RISING')score+=4;if(Math.abs(m.acceleration)>=8)score+=2;}score=Math.min(15,score);return {status:'OK',score:round(score),band:score>=11?'HIGH':score>=6?'MEDIUM':'LOW'};}
function lrs(sig,en,nov,flow,dqv){if([sig,en,nov,flow,dqv].some(x=>x.status!=='OK'))return {status:'NOT_SCORABLE',raw_lrs:null,final_lrs:null,reasons:['REQUIRED_DEPENDENCY_NOT_READY']};const sm={NONE:0,CANDIDATE:6,FORMING:12,ACTIVE:22,SUSTAINED:26};let ss=sm[sig.lifecycle]||0;if(sig.signal_type==='TWO_SIDED_ESCALATION')ss=Math.min(35,ss+7);else if(sig.signal_type==='GOAL_PRESSURE_ACTIVE')ss=Math.min(35,ss+5);const em={BLOCKED_DATA:0,WAIT_BUILDING:8,WAIT_CONFIRMING:11,OPEN_EARLY:23,OPEN_CORE:30,OPEN_FADING:21,LATE_DECAY:10,LATE_REVERSAL:5},es=em[en.substate]||0,ns=Math.min(20,nov.score||0),fs=Math.min(15,flow.score||0),raw=Math.min(100,ss+es+ns+fs),cc={HIGH:100,MEDIUM:84,LOW:69}[dqv.confidence]||69,dc=dqv.validation_status==='VALID'?100:dqv.validation_status==='CAUTION'?79:0;return {status:'OK',raw_lrs:round(raw),final_lrs:round(Math.min(raw,cc,dc)),components:{signal:ss,entry:es,novelty:round(ns),flow:round(fs)},caps:{confidence:cc,dq:dc},phase_a_eligible:false};}
function publicFixture(item){return {fixture_id:item?.fixture?.id??null,league:{id:item?.league?.id??null,name:item?.league?.name||'Unknown',country:item?.league?.country||'',logo:item?.league?.logo||null},teams:{home:{id:item?.teams?.home?.id??null,name:item?.teams?.home?.name||'Home',logo:item?.teams?.home?.logo||null},away:{id:item?.teams?.away?.id??null,name:item?.teams?.away?.name||'Away',logo:item?.teams?.away?.logo||null}},goals:{home:item?.goals?.home??null,away:item?.goals?.away??null},status:{short:item?.fixture?.status?.short||'',elapsed:item?.fixture?.status?.elapsed??null,long:item?.fixture?.status?.long||''},venue:item?.fixture?.venue?.name||null,date:item?.fixture?.date||null};}
function analyzePreFixture(captureRows,evidenceRows){
  const latest=captureRows[0],item=safeJson(latest.fixture_json,{}),pub=publicFixture(item);
  const kindCount=k=>evidenceRows.filter(x=>x.evidence_kind===k&&Number(x.item_count||0)>0).length;
  const lineups=kindCount('LINEUPS'),odds=kindCount('PRE_ODDS'),pred=kindCount('PREDICTIONS'),stand=kindCount('STANDINGS'),h2h=kindCount('H2H'),hf=kindCount('HOME_FORM'),af=kindCount('AWAY_FORM');
  const kickoff=Date.parse(pub.date||0),mins=Number.isFinite(kickoff)?Math.round((kickoff-Date.now())/60000):null;
  const contextScore=Math.min(100,10+(stand?20:0)+(hf?10:0)+(af?10:0)+(h2h?10:0)+(odds?20:0)+(lineups?15:0)+(pred?5:0));
  const blockers=[];if(!stand)blockers.push('STANDINGS');if(!hf||!af)blockers.push('RECENT_FORM');if(!odds)blockers.push('PRE_ODDS');if(mins!=null&&mins<=90&&!lineups)blockers.push('LINEUPS');
  return {...pub,received_at:latest.received_at,capture_count:captureRows.length,minutes_to_kickoff:mins,
    pre_context:{status:contextScore>=75?'READY':contextScore>=40?'PARTIAL':'COLLECTING',context_score:contextScore,lineups_payloads:lineups,pre_odds_payloads:odds,prediction_payloads:pred,standings_payloads:stand,h2h_payloads:h2h,home_form_payloads:hf,away_form_payloads:af,
      standings_status:stand?'AVAILABLE':'PENDING',recent_form_status:hf&&af?'AVAILABLE':hf||af?'PARTIAL':'PENDING',h2h_status:h2h?'AVAILABLE':'PENDING',market_status:odds?'AVAILABLE':'PENDING',prediction_role:'BENCHMARK_ONLY',blockers},
    evidence:{raw_captures:captureRows.length,lineups_payloads:lineups,pre_odds_payloads:odds,prediction_payloads:pred,standings_payloads:stand,h2h_payloads:h2h,home_form_payloads:hf,away_form_payloads:af}};
}

function normalizeLiveMarketEvidence(rows,pub){
  if(!rows?.length)return {status:'NOT_AVAILABLE',payloads:0,latest_received_at:null,normalized:false,markets:[],valid_markets:0,invalid_markets:0};
  const latest=rows.at(-1),payload=safeJson(latest.payload_json,{});
  let markets=[];
  try{markets=legacyMarketEngine.normalizeLiveMarkets(Array.isArray(payload?.response)?payload.response:[],{homeName:pub.teams.home.name,awayName:pub.teams.away.name})||[]}catch{}
  const compact=markets.slice(0,12).map(m=>({
    category:m.category,market:m.bet||m.category,main_line:m.main_line??null,feed_status:m.feed_status||null,
    integrity:m.integrity||null,
    values:(m.values||[]).slice(0,6).map(v=>({value:v.value,odd:v.odd??null,handicap:v.handicap??null,main:v.main??null,suspended:!!v.suspended,selection_side:v.selection_side??null,selection_outcome:v.selection_outcome??null}))
  }));
  const valid=compact.filter(m=>m.integrity?.valid!==false).length,invalid=compact.filter(m=>m.integrity?.valid===false).length;
  const categories=[...new Set(compact.map(m=>m.category).filter(Boolean))];
  return {status:compact.length?'AVAILABLE':'UNUSABLE',payloads:rows.length,latest_received_at:latest.received_at,normalized:compact.length>0,valid_markets:valid,invalid_markets:invalid,categories,markets:compact};
}
function analyzeFixture(captureRows,evidenceRows){const latest=captureRows[0],item=safeJson(latest.fixture_json,{}),pub=publicFixture(item),statsRows=evidenceRows.filter(x=>x.evidence_kind==='STATISTICS'&&Number(x.non_null_value_count||0)>0).sort((a,b)=>Date.parse(a.received_at)-Date.parse(b.received_at)),eventRows=evidenceRows.filter(x=>x.evidence_kind==='EVENTS'&&Number(x.item_count||0)>0).sort((a,b)=>Date.parse(a.received_at)-Date.parse(b.received_at)),marketRows=evidenceRows.filter(x=>x.evidence_kind==='LIVE_ODDS'&&Number(x.item_count||0)>0).sort((a,b)=>Date.parse(a.received_at)-Date.parse(b.received_at)),events=eventRows.length?normalizeEvents(safeJson(eventRows.at(-1).payload_json,{})):(Array.isArray(item?.events)?item.events:[]),observations=statsRows.map(r=>({received_at:r.received_at,elapsed:nearestElapsed(captureRows,r.received_at,pub.status.elapsed||0),stats:normalizeStats(safeJson(r.payload_json,{}))})),latestStats=observations.at(-1)?.stats||{},feat=intervalFeatures(observations.at(-2),observations.at(-1),item,events),p=pressure(feat),t=threat(feat),tp=tempo(feat),c=control(feat,p),m=momentum(observations,item,events),ms=matchState(p,t,tp,c),gp=goalPressure(p,t,ms,tp,m),sig=signal(gp),dqv=dq(latestStats,observations,feat,statsRows.at(-1)?.received_at||latest.received_at),en=entry(sig,dqv,gp),nov=novelty(sig,en,feat,events,pub.status.elapsed||0),flow=flowChange(p,ms,m),lr=lrs(sig,en,nov,flow,dqv),market=normalizeLiveMarketEvidence(marketRows,pub),final_gate={state:lr.status!=='OK'?'BLOCKED_DATA':en.state!=='OPEN'?'WAIT_ENTRY':!marketRows.length?'WAIT_MARKET':market.valid_markets===0?'BLOCKED_MARKET_INTEGRITY':'WAIT_MARKET_CONFIRM',reason:lr.status!=='OK'?'LRS_NOT_SCORABLE':en.state!=='OPEN'?'ENTRY_NOT_OPEN':!marketRows.length?'LIVE_MARKET_NOT_CAPTURED':market.valid_markets===0?'NO_VALID_NORMALIZED_MARKET':'MARKET_AVAILABLE_NEEDS_SELECTION_CONFIRM'};return {...pub,received_at:latest.received_at,capture_count:captureRows.length,stats_evidence_count:statsRows.length,event_evidence_count:eventRows.length,engine:{features:{status:feat.status,reasons:feat.reasons||[]},pressure:p,threat:t,momentum:m,tempo:tp,control:c,match_state:ms,goal_pressure:gp,signal:sig,dq:dqv,entry:en,novelty:nov,flow_change:flow,lrs:lr,market,final_gate,reasons:[...(feat.reasons||[]),...(lr.reasons||[])]},evidence:{raw_captures:captureRows.length,stats_payloads:statsRows.length,event_payloads:eventRows.length,live_odds_payloads:marketRows.length,latest_stats_received_at:statsRows.at(-1)?.received_at||null,latest_events_received_at:eventRows.at(-1)?.received_at||null,latest_market_received_at:marketRows.at(-1)?.received_at||null}};}
async function loadData(env){const caps=await env.DB.prepare(`SELECT capture_id,fixture_id,match_clock,status_short,received_at,fixture_json,event_count,stats_value_count,has_events,has_stats FROM raw_fixture_captures ORDER BY received_at DESC LIMIT 500`).all(),ev=await env.DB.prepare(`SELECT evidence_id,fixture_id,evidence_kind,received_at,item_count,non_null_value_count,payload_json FROM raw_fixture_evidence ORDER BY received_at DESC LIMIT 800`).all(),byFx=new Map(),byEv=new Map();for(const r of caps.results||[]){const k=String(r.fixture_id);if(!byFx.has(k))byFx.set(k,[]);byFx.get(k).push(r);}for(const r of ev.results||[]){const k=String(r.fixture_id);if(!byEv.has(k))byEv.set(k,[]);byEv.get(k).push(r);}return {byFx,byEv};}
export async function buildV2Overview(env){
  const {byFx,byEv}=await loadData(env),matches=[],pre_matches=[];
  const now=Date.now(),preHorizon=now+12*60*60*1000;
  for(const [id,rows] of byFx){
    const latest=rows[0],item=safeJson(latest.fixture_json,{}),status=latest.status_short;
    if(LIVE.has(status)){matches.push(analyzeFixture(rows,byEv.get(id)||[]));continue;}
    if(status==='NS'){
      const dt=Date.parse(item?.fixture?.date||0);
      if(Number.isFinite(dt)&&dt>=now-10*60*1000&&dt<=preHorizon)pre_matches.push(analyzePreFixture(rows,byEv.get(id)||[]));
    }
  }
  matches.sort((a,b)=>{const la=a.engine.lrs.final_lrs,lb=b.engine.lrs.final_lrs;if(la!==null||lb!==null)return (lb??-1)-(la??-1);return Date.parse(b.received_at)-Date.parse(a.received_at);});
  pre_matches.sort((a,b)=>(a.minutes_to_kickoff??999999)-(b.minutes_to_kickoff??999999));
  const cycle=await env.DB.prepare('SELECT * FROM capture_cycles ORDER BY started_at DESC LIMIT 1').first(),
    counts=await env.DB.prepare(`SELECT COUNT(*) raw_snapshots,COUNT(DISTINCT fixture_id) fixtures,SUM(has_events) snapshots_with_events,SUM(has_stats) snapshots_with_stats,MIN(received_at) first_received_at,MAX(received_at) last_received_at FROM raw_fixture_captures`).first(),
    evidence=await env.DB.prepare(`SELECT COUNT(*) evidence_rows,COUNT(DISTINCT fixture_id) evidence_fixtures,SUM(CASE WHEN evidence_kind='EVENTS' AND item_count>0 THEN 1 ELSE 0 END) event_payloads,SUM(CASE WHEN evidence_kind='STATISTICS' AND non_null_value_count>0 THEN 1 ELSE 0 END) stats_payloads,SUM(CASE WHEN evidence_kind='LINEUPS' AND item_count>0 THEN 1 ELSE 0 END) lineups_payloads,SUM(CASE WHEN evidence_kind='LIVE_ODDS' AND item_count>0 THEN 1 ELSE 0 END) live_odds_payloads,SUM(CASE WHEN evidence_kind='PRE_ODDS' AND item_count>0 THEN 1 ELSE 0 END) pre_odds_payloads FROM raw_fixture_evidence`).first();
  const scorable=matches.filter(m=>m.engine.lrs.status==='OK');
  const active=scorable.filter(m=>m.engine.signal.lifecycle==='ACTIVE');
  const open=scorable.filter(m=>m.engine.entry.state==='OPEN');
  const top_live=scorable.slice(0,4).map(m=>({fixture_id:m.fixture_id,lrs:m.engine.lrs.final_lrs,signal:m.engine.signal.signal_type,entry:m.engine.entry.state,state:m.engine.match_state.primary_state}));
  const lastRaw=Date.parse(counts?.last_received_at||0),ageSec=Number.isFinite(lastRaw)?Math.max(0,Math.round((Date.now()-lastRaw)/1000)):null;
  const health=cycle?.status==='ERROR'?'ERROR':ageSec!=null&&ageSec>900?'STALE':/RATE/.test(cycle?.stop_reason||'')?'BACKOFF':'ONLINE';
  return {ok:true,schema:'FE_V2_APP_OVERVIEW_V2',app_version:'V2.1.0-ALPHA',engine_version:'DEV0.5-DATA-PLANE',generated_at:new Date().toISOString(),
    matches,pre_matches,scan:{live_scorable:scorable.length,active_signals:active.length,entry_open:open.length,top_live},
    system:{health,last_raw_received_at:counts?.last_received_at||null,last_raw_age_sec:ageSec,next_capture_target_sec:180},
    collector:{last_cycle:cycle||null,counts:counts||{},evidence:evidence||{}},
    validation:{null_zero_guard:'PASS',unit_regression:'10/10 PASS',harness_regression:'20/20 PASS',phase_a:'NOT_ELIGIBLE',reason:'PHASE_A_REQUIRES_REAL_STATS_MULTI_SNAPSHOT_AND_QC'}};
}
export async function buildV2Match(env,fixtureId){const {byFx,byEv}=await loadData(env),rows=byFx.get(String(fixtureId))||[];if(!rows.length)return null;return analyzeFixture(rows,byEv.get(String(fixtureId))||[]);}
